server:
  port: 8020
spring:
  data:
    elasticsearch:
      cluster-name: elasticsearch_xianguo
      cluster-nodes: localhost
  datasource:
      driverClassName: com.mysql.jdbc.Driver
      username: root
      password: alixian
      url: jdbc:mysql://localhost:3306/moyu_db?useUnicode=true&characterEncoding=utf-8&useSSL=true
      type: org.apache.tomcat.jdbc.pool.DataSource
  profiles:
    active: local
  application:
    name: elastic
mybatis:
  mapper-locations: classpath*:/mapper/**/*Mapper.xml
  type-aliases-package: com.leno.elastic.dal.model
logging:
  config: classpath:elastic-logback.xml
